config/routes.rb
Rails.application.routes.draw do
  root 'cards#index'
  resources :cards, only: [:index, :new, :create, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates_presence_of [:front, :back]
  def self.search(termo)
    if termo
      all.select { |card| card.include?(termo) }
    else
      all
    end
  end

  def include?(text)
    front.upcase.include?(text.upcase) ||
      back.upcase.include?(text.upcase)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @flag = params[:search].blank?
    @cards = Card.search params[:search]
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new front: params[:card][:front], back: params[:card][:back]
    @card.save
    redirect_to @card
  end

  def show
    @card = Card.find params[:id]
  end

  def destroy
    @cards = Card.find params[:id]
    @cards.delete
    redirect_to cards_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_card.html.erb
<tr>
  <td>
    <%= "#{card.front}" %>
  </td>
  <td>
    <%= "#{card.back}" %>
  </td>
  <td>
    <%= link_to 'Delete card', card, method: :delete %>
  </td>
</tr>

app/views/cards/index.html.erb
<%= form_tag cards_path, method: 'get', class: "col s6 center-align" do %>
<div class="input-field col s6">
  <%= label_tag :search, 'Search for:', class: "active" %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag 'Search card', name: nil, class: "waves-effect waves-light btn" %>
</div>
<% end %>

<ul class="collection with-header">
  <li class="collection-header">
    <h3>
      <% if @flag %>
        <%= 'Registered cards' %>
      <% else %>
        <%= 'Cards found' %>
      <% end %>
    </h3>
  </li>
  <table>
    <thead>
      <tr>
        <th>
          Frente
        </th>
        <th>
          Verso
        </th>
        <th>
          Delete
        </th>
      </tr>
    </thead>
    <tbody>
    <% @cards.each do |card| %>
      <%= link_to render(partial: card), card %>
    <% end %>
    </tbody>
  </table>
</ul>

app/views/cards/new.html.erb
<%= form_for @card, class: "col s6 center-align" do |f| %>
  <div class="input-field col s6">
    <%= f.label :front, 'Front view' %>
    <%= f.text_field :front %>
  </div>
  <div class="input-field col s6">
    <%= f.label :back, 'Back view' %>
    <%= f.text_field :back %>
  </div>
    <%= f.submit class: "waves-effect waves-light btn" %>

<% end %>

app/views/cards/show.html.erb
<ul class="collection with-header">
  <li class="collection-header"><h5>Card</h5></li>
  <li class="collection-item"><%= render partial: @card %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MedicalCards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/menu' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_menu.erb
<nav class="maa blue lighten-3">
  <div class="nav-wrapper container">
    <%= link_to "Card System", root_path, class: "brand-logo" %>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to 'Home', cards_path %></li>
      <li><%= link_to 'Create new card', new_card_path %></li>
    </ul>
  </div>
</nav>